name: Push to DockerHub

on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      -
        name: Install pip Dependencies in venv
        run: |
          ls
          cd ./oneplus/
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -r ../requirements.txt
          python manage.py test
  
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - 
        name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_HUB_USERNAME }}/hello-oneplus:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Pull Image on EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOSTNAME: ${{ vars.SSH_HOST }}
          USER_NAME: ${{ vars.SSH_USER }}
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ vars.SSH_HOST }} 'docker run --rm --name somerunner ${{ vars.DOCKER_HUB_USERNAME }}/hello-oneplus:latest'
